### ISSUE TITLE
Error deploying after initial deploy, v0.7.0

### ISSUE THREAD

**Issue by andreasantarl** [awslabs/chalice#287]
I'm unable to re-deploy my project after the initial deploy. I keep getting the error "An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: myapp-dev". This wasn't an issue with version 0.6.0., and I'm only seeing this after updating to 0.7.0.

**Comment by freaker2k7** [comment]
Same here!

**Comment by ramiah11** [comment]
+1

**Comment by thenaturalist** [comment]
It means someone already deployed an app with the same name in your AWS instance. Rename the app to a name that is not already used and the deploy should work fine.

**Comment by jamesls** [comment]
Just wanted to follow up here.  I believe this is now fixed.  Please try out the latest version (1.0.0b1) as of today and let me know if you're still seeing issues.

**Comment by badisa** [comment]
@jamesls I am still seeing this issue with chalice 1.0.1. Using python 3.6.

Note that a collaborator deployed the app initially and I am trying to deploy a modification I made.

**Comment by MudlaffP** [comment]
In my case the cause for this error was lack of entry about stage in `deployment.json`

**Comment by gopimicky** [comment]
Is this issue got fixed.  I am trying to do chalice to deploy a function, which is triggerd by SQS event.

I have deployed it successfully from local dev.  When I try to deploy it from the CI/CD pipeline, I am seeing the following error:
`
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the CreateEventSourceMapping operation: An event source mapping with SQS arn (" arn:aws:sqs:eu-west-1:xxxxxxxxxxxxxx:xxxxxxxxxxxxxx") and function ("xxxxxxxxx") already exists. Please update or delete the existing mapping with UUID 04c823b2-xxxxx-xxxxx-xxxxxxx-xxxxxxxxxxx
` 

`
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (ResourceConflictException) when calling the 
 CreateEventSourceMapping operation: An event source mapping with SQS arn (" arn:aws:sqs:eu-west-1:xxxxxxxxxxxxxx:xxxxxxxxxxxxxx") and function ("xxxxxxxxx") already exists. Please update or 
 delete the existing mapping with UUID  04c823b2-xxxxx-xxxxx-xxxxxxx-xxxxxxxxxx
`

Only way to get aroud this is to delete the Lambda Triggers in SQS(manually/aws cli).  Is this an expected behaviour on chalice deploy?

**Comment by JacksonKontny** [comment]
@jamesls I too am still having this issue. I am using:

chalice 1.6.2
python 3.7.3

The issue I get is exactly as @gopimicky reported above.
